### ISSUE TITLE
Crash with broadcast

### ISSUE THREAD

**Issue by oschulz** [wsmoses/Enzyme.jl#71]
(No sure whether to report this here or on the main Enzyme repo.)

Enzyme seems to crash with `broadcast!` (non-allocating). This works fine:

```julia
using Enzyme

function foo_nobc!(R, A, B)
    @assert eachindex(R) == eachindex(R) == eachindex(B)
    @inbounds @simd for i in eachindex(R)
        R[i] = A[i] + B[i]
    end
    return nothing
end

function foo_bc!(R, A, B)
    broadcast!(+, R, A, B)
    return nothing
end


A = rand(10); B = rand(10); R = similar(A)
dA = zero(A); dB = zero(B); dR = fill!(similar(R), 1)

foo_nobc!(R, A, B)
foo_bc!(R, A, B)

autodiff(foo_nobc!, Duplicated(R, dR), Duplicated(A, dA), Duplicated(B, dB))
```

But 

```julia
autodiff(foo_bc!, Duplicated(R, dR), Duplicated(A, dA), Duplicated(B, dB))
```

goes boom:

```
mod: ; ModuleID = 'text'
source_filename = "text"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128-ni:10:11:12:13"
target triple = "x86_64-pc-linux-gnu"

@exception.4 = private unnamed_addr constant [10 x i8] c"exception\00", align 1

; Function Attrs: readnone
declare {}*** @julia.ptls_states() local_unnamed_addr #0

declare nonnull {} addrspace(10)* @jl_invoke({} addrspace(10)*, {} addrspace(10)** nocapture readonly, i32, {} addrspace(10)*) local_unnamed_addr
[...]
```

In principle, Enzyme should be able to support (non-allocating) broadcasts, right?

**Comment by wsmoses** [comment]
I'm not quite sure why this remains an invoke (@vchuravy). Also as an aside we should probably early catch all the accidental jl_invoke and jl_apply_generic calls rather than letting the error get handled later in a worse way

```
@code_typed foo_bc!(R, A, B)
CodeInfo(
1 ─     invoke Main.broadcast!(Main.:+::typeof(+), _2::Vector{Float64}, _3::Vector{Float64}, _4::Vector{Float64})::Any
└──     return Main.nothing
) => Nothing
```

Adding support for jl_apply_generic and jl_invoke is in progress though so this _will_ be supported [and was incidentally what was working on yesterday]. Regardless we should determine why this remained an invoke instead of proper lowering

**Comment by oschulz** [comment]
Thanks - having broadcasting support would be awesome, since it's such an easy path to code that works on both CPU and GPU.

**Comment by wsmoses** [comment]
As a note here the operation `broadcast!(+, R, A, B)` allocates and returns a new array. The partial GC support will eventually handle this, but it currently exercises the use of the one function (jl_copy_array) which is not yet handled,

**Comment by oschulz** [comment]
Why does `broadcast!(+, R, A, B)` allocate?

**Comment by vchuravy** [comment]
Because `broadcast!` checks whether the arguments are aliased with the output,
and if so performs a copy of the input that is aliased.

https://github.com/JuliaLang/julia/blob/2dd34c150d5081222c2df1dc788202c111d01c17/base/broadcast.jl#L978

This then looks in the code like such, and array_copy is both an allocation and a copy and as such turned out to be non-trivial.

```
44 ┄ %104 = φ (#41 => %100, #42 => false, #43 => false)::Bool
└───        goto #46 if not %104
45 ─ %106 = $(Expr(:foreigncall, :(:jl_array_copy), Ref{Vector{Float64}}, svec(Any), 0, :(:ccall), Core.Argument(3)))::Vector{Float64}
```

**Comment by oschulz** [comment]
Ah forgot about that! So while in the case above, no copy is actually made (no aliasing), the code for the copy is still in there, of course.

**Comment by vchuravy** [comment]
#79 will be able to handle this, as long as there is no "complicated" aliasing

**Comment by oschulz** [comment]
The test case above seem to work fine now!
